### ISSUE TITLE
Linkedin Icon bei Kontakt-Icons

### ISSUE THREAD

**Issue by hennyangel** [hennyangel/website-henrike-engel#3]
Linkedin Icon fehlt

**Comment by builtin-malloc** [comment]
Das Linkedin Logo ist ziemlich fett.
![Screenshot from 2024-08-18 21-09-09](https://github.com/user-attachments/assets/38de58dd-0833-491d-b75c-d50078875bf4)

**Comment by hennyangel** [comment]
Ich änder es ab
